# This is a basic workflow that is manually triggered

name: Extract Character Code From Image

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    inputs:
      url:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Image URL to extract character from'
        # Input has to be provided for the workflow to run
        required: true

jobs:
  extract:
    runs-on: ubuntu-latest
    name: Extract Character Code
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '10'
      - run: npm install
        working-directory: 'Tools/Character Extractor'
      - run: npm run convert ${{ github.event.inputs.url }}
        working-directory: 'Tools/Character Extractor'
